language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

script:
  - run-prove oclcl-test.asd
