language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=abcl
    - env: LISP=clisp

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

script:
  - run-prove oclcl-test.asd
